language: erlang

# Choose which platforms you want your builds run against (done in parallel)
env:
   #- ST=Squeak-4.4
   - ST=Squeak-4.5
   - ST=Squeak-Trunk

# For SqueakSSL
before_install:
   - sudo apt-get -qq install libssl0.9.8:i386

# Boilerplate ... should be no reason to edit the install section
install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/SWTI2014/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd SWTI2014-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh
   - ln -s $PROJECT_HOME/images $IMAGES_PATH/travis_images
   - ls $IMAGES_PATH
   - echo $IMAGES_PATH
   - ls $IMAGES_PATH/travis_images
   - ls $PROJECT_HOME/images
   - echo $PROJECT_HOME

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh # -verbose 
