language: smalltalk
sudo: false
smalltalk:
  - Squeak-trunk
  - Squeak-5.2
#  - Squeak-5.1
#  - Squeak-5.0
  
#matrix:
#    allow_failures:
#        - smalltalk: Squeak-5.1
#        - smalltalk: Squeak-5.0
#        - smalltalk: Squeak-5.0 
